Create ru.json
TDesktop-x64/Localization pull request #5
Opened 2020-09-08 23:27 UTC by winqooq

Draft translation into Russian

2020-10-15 03:01 UTC, c0re100 commented
If #6 #5 ready to merge, ping me :)

2020-10-19 19:05 UTC, winqooq commented
@c0re100 done :)

2020-10-21 19:12 UTC, c0re100 requested changes

2020-10-21 23:57 UTC, winqooq commented on ru.json
> +    "lng_profile_gifs#few": "{count} GIF",
it has no translation in either Russian or Ukrainian, it is used in this form
just "GIF"

2020-10-22 00:00 UTC, winqooq commented on ru.json
> +    "lng_media_selected_gif#few": "{count} GIF",
sorry, but without this data, this graph will look like this
![Good](https://user-images.githubusercontent.com/55299850/96802484-9b282b80-1412-11eb-88b3-2cfcc83db39e.PNG)
![bad](https://user-images.githubusercontent.com/55299850/96802485-9bc0c200-1412-11eb-9d24-f1fe8113c5a1.PNG)

2020-10-22 00:06 UTC, c0re100 commented on ru.json
> +    "lng_media_selected_gif#few": "{count} GIF",
Look like buggy on customize language loader, I will fix it later.
So it is safe to remove this 2 string.

2020-10-22 00:07 UTC, c0re100 commented on ru.json
> +    "lng_profile_gifs#few": "{count} GIF",
I mean `few` and `many`

2020-10-22 00:59 UTC, c0re100 commented on ru.json
> +    "lng_profile_gifs#few": "{count} GIF",
deleted by mistake lol
only have #one and #other.

2020-10-22 01:03 UTC, c0re100 approved these changes

2020-10-22 01:04 UTC, merged

2020-10-22 01:04 UTC, c0re100 commented
Thank you~

2020-10-22 01:44 UTC, c0re100 commented
hmmm.......
Look like Russian can't display gif header text correctly.....
Some group have gif header, but some haven't......
I don't know why, so confused................

2020-10-22 10:12 UTC, winqooq commented
@c0re100 because previously deleted lines (#few and #many) are required for Russian and Ukrainian languages

(you can see which variables correspond to the language here https://translations.telegram.org/?l=language%2Fnew)

look in the Kotatogram Desktop (https://github.com/kotatogram/kotatogram-desktop), maybe you can find there a solution of this problem

2020-10-23 00:34 UTC, c0re100 commented
> @c0re100 because previously deleted lines (#few and #many) are required for Russian and Ukrainian languages
> ![Screenshot_2020-10-22 Translations(1)](https://user-images.githubusercontent.com/55299850/96857997-6050e280-1468-11eb-8f6f-1dbae8a572aa.png)
> (you can see which variables correspond to the language here https://translations.telegram.org/?l=language%2Fnew by choosing the base language)
> 
> look in the Kotatogram Desktop (https://github.com/kotatogram/kotatogram-desktop), maybe you can find there a solution of this problem

WTF is telegram doing......lol
so confusing...
I guess I can fix it on client side.

2020-10-24 15:46 UTC, winqooq commented
@c0re100, tell me, do i have to create a new pull to update the translation?

2020-10-24 15:51 UTC, c0re100 commented
> @c0re100, tell me, do i have to create a new pull to update the translation?

No need, cause still in draft stage.
You can PR when 2.4.4.2 out.

2020-10-26 19:25 UTC, winqooq commented
> No need, cause still in draft stage.
> You can PR when 2.4.4.2 out.

Ok, can you tell me how exactly can I update the localization

_maybe I'll just send you a ready *.json translation? :)_

2020-10-26 20:29 UTC, c0re100 commented
> > No need, cause still in draft stage.
> > You can PR when 2.4.4.2 out.
> 
> Ok, can you tell me how exactly can I update the localization
> 
> _maybe I'll just send you a ready *.json translation? :)_

If you don't know how to use git.
You can delete your repo and fork again, then create pull request with update.

2020-10-26 20:43 UTC, winqooq commented
> You can delete your repo and fork again, then create pull request with update.

ok, got it.

what should I choose "Create pull request" or "Create draft pull request" when opening a pull request? _so that I can update the translation in the future without creating a new pull request every time_